---
# first testing via git actions

apiVersion: v1
kind: Pod
metadata:
  name: poda
  labels: 
    app: apache
spec:
  containers:
    - name: apache
      image: httpd
      ports: 
        - containerPort: 80

# making this to get exposed outside
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
#  type: NodePort     # for NodePort  [ kubectl port-forward pod/poda 8080:80 _using this can be accessed on the host(laptop browser)]
type: ClusterIP     # for ClusterIP [accessible via cluster's internal IP]
  selector:
    app: apache
  ports:
    - protocol: TCP     # for ClusterIP
      port: 80
      targetPort: 80
#      nodePort: 30080     # for NodePort